[package]
name = "ds-examples"
edition.workspace = true
version.workspace = true
license = "LGPL-3.0"

[[bin]]
name = "ds-examples"
path = "src/main.rs"

[[bin]]
name = "stereo-test"
path = "src/stereo_test.rs"

[[bin]]
name = "taiyang-clone"
path = "src/taiyang_clone.rs"

[[bin]]
name = "small-blocks"
path = "src/small_blocks.rs"

[[bin]]
name = "sfz-test"
path = "src/sfz_test.rs"

[[bin]]
name = "sfz-play"
path = "src/sfz_play.rs"

[[bin]]
name = "vel-test"
path = "src/vel_test.rs"

[dependencies]
dysonphere-core = { path = "../dysonphere-core" }
dysonphere-soundfont = { path = "../dysonphere-soundfont" }
hound = "3.5"
lazy_static = "1.4"
